-- 0012 · Robot serial numbers are generated by the PMS: 8 digits, unique, permanent.
-- Robot ID stays product code + running number ('saibya02', 'ductcleaning01'); the serial is a separate,
-- auto-generated number ('48213907') and still never stands in for the ID.

-- ── 8-digit serial generator ────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION pms_new_serial_number() RETURNS text
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
  s text;
BEGIN
  LOOP
    s := (10000000 + floor(random() * 90000000))::bigint::text;   -- 10000000 … 99999999
    EXIT WHEN NOT EXISTS (SELECT 1 FROM robots WHERE upper(serial_number) = s);
  END LOOP;
  RETURN s;
END $$;

-- Robots registered before this migration get a generated serial; the old free-text value is kept in notes.
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN SELECT robot_id, serial_number FROM robots WHERE serial_number !~ '^[0-9]{8}$' ORDER BY created_at LOOP
    UPDATE robots
       SET serial_number = pms_new_serial_number(),
           notes = concat_ws(E'\n', nullif(notes, ''), 'Previous serial number: ' || r.serial_number)
     WHERE robot_id = r.robot_id;
  END LOOP;
END $$;

ALTER TABLE robots ALTER COLUMN serial_number SET DEFAULT pms_new_serial_number();
ALTER TABLE robots ADD CONSTRAINT robots_serial_8_digits CHECK (serial_number ~ '^[0-9]{8}$');
CREATE TRIGGER robots_serial_permanent BEFORE UPDATE ON robots
  FOR EACH ROW EXECUTE FUNCTION pms_immutable_columns('serial_number');

-- ── Product code 'duct_cleaning' → 'ductcleaning' (Robot IDs 'ductcleaning01', …) ──
-- Only while no robot uses the old code: Robot IDs are permanent and are never renamed.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM products WHERE code = 'duct_cleaning')
     AND NOT EXISTS (SELECT 1 FROM products WHERE code = 'ductcleaning')
     AND NOT EXISTS (SELECT 1 FROM robots r JOIN products p ON p.id = r.product_id WHERE p.code = 'duct_cleaning') THEN
    ALTER TABLE products DISABLE TRIGGER products_code_permanent;
    UPDATE products SET code = 'ductcleaning' WHERE code = 'duct_cleaning';
    ALTER TABLE products ENABLE TRIGGER products_code_permanent;
  END IF;
END $$;
