-- 0014 · Robot registration and ingest-client creation as database functions.
-- The rules live in the database (the storage service), so the server's "Register robot" and the storage
-- seed apply exactly the same ones without sharing code:
--   Robot ID = product code + running number ('saibya02', 'ductcleaning01'), never reused;
--   serial number = 8 unique digits (column default, migration 0012);
--   first ownership period (Arnobot), live_state / connectivity / dispatch rows.
-- Errors: P0002 = not found, 22023 = invalid input.

CREATE OR REPLACE FUNCTION pms_format_robot_id(p_code text, p_running integer) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT p_code || CASE WHEN p_running < 10 THEN '0' ELSE '' END || p_running::text
$$;

CREATE OR REPLACE FUNCTION pms_register_robot(
  p_product_id   uuid,
  p_revision_id  uuid,
  p_notes        text,
  p_created_by   uuid,
  p_company_id   uuid DEFAULT NULL
) RETURNS TABLE (new_robot_id text, new_serial_number text)
LANGUAGE plpgsql AS $$
DECLARE
  prod     record;
  running  integer;
  rid      text;
  serial   text;
  company  uuid;
BEGIN
  -- Row lock on the product: concurrent registrations get consecutive running numbers.
  SELECT p.id, p.code, p.next_running_number INTO prod
    FROM products p WHERE p.id = p_product_id AND p.deleted_at IS NULL FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'product not found' USING ERRCODE = 'P0002';
  END IF;
  IF p_revision_id IS NOT NULL AND NOT EXISTS (
       SELECT 1 FROM hardware_revisions h WHERE h.id = p_revision_id AND h.product_id = prod.id AND h.deleted_at IS NULL) THEN
    RAISE EXCEPTION 'hardware revision does not belong to this product' USING ERRCODE = '22023';
  END IF;

  -- Skip any running number already used (e.g. robots imported with explicit IDs). IDs are never reused.
  running := prod.next_running_number;
  LOOP
    rid := pms_format_robot_id(prod.code, running);
    EXIT WHEN NOT EXISTS (SELECT 1 FROM robots r WHERE r.robot_id = rid OR (r.product_id = prod.id AND r.running_number = running));
    running := running + 1;
  END LOOP;

  INSERT INTO robots (robot_id, product_id, hardware_revision_id, running_number, notes, created_by)
  VALUES (rid, prod.id, p_revision_id, running, p_notes, p_created_by)
  RETURNING robots.serial_number INTO serial;
  UPDATE products SET next_running_number = running + 1 WHERE id = prod.id;

  company := coalesce(p_company_id, (SELECT c.id FROM companies c WHERE lower(c.name) = 'arnobot' AND c.deleted_at IS NULL LIMIT 1));
  IF company IS NULL THEN
    RAISE EXCEPTION 'no owner company (seed the Arnobot company first)' USING ERRCODE = '22023';
  END IF;
  INSERT INTO company_assignment_history (robot_id, company_id, valid_from, reason, created_by)
  VALUES (rid, company, now(), 'Registered', p_created_by);

  INSERT INTO live_state (robot_id) VALUES (rid);
  INSERT INTO connectivity (robot_id, updated_by) VALUES (rid, p_created_by);
  INSERT INTO dispatch_warranty (robot_id, updated_by) VALUES (rid, p_created_by);

  new_robot_id := rid;
  new_serial_number := serial;
  RETURN NEXT;
END $$;

-- Who may push data in: a robot client speaks for exactly its own robot, a GCS client for the listed ones.
-- The key itself is generated by the caller; only its prefix and SHA-256 are stored.
CREATE OR REPLACE FUNCTION pms_create_ingest_client(
  p_name        text,
  p_kind        text,
  p_robot_ids   text[],
  p_notes       text,
  p_key_prefix  text,
  p_key_hash    text,
  p_created_by  uuid
) RETURNS uuid
LANGUAGE plpgsql AS $$
DECLARE
  cid uuid;
BEGIN
  IF p_kind = 'robot' AND coalesce(array_length(p_robot_ids, 1), 0) <> 1 THEN
    RAISE EXCEPTION 'a robot ingest client speaks for exactly one robot' USING ERRCODE = '22023';
  END IF;
  INSERT INTO ingest_clients (name, kind, notes, created_by) VALUES (p_name, p_kind, p_notes, p_created_by) RETURNING id INTO cid;
  INSERT INTO ingest_client_robots (client_id, robot_id, created_by)
  SELECT cid, r, p_created_by FROM unnest(coalesce(p_robot_ids, '{}'::text[])) AS r;
  INSERT INTO ingest_keys (client_id, key_prefix, key_hash, created_by) VALUES (cid, p_key_prefix, p_key_hash, p_created_by);
  RETURN cid;
END $$;
